//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoClicker_Mizer1.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sol Tık")]
        public string D_Hangi_Tus {
            get {
                return ((string)(this["D_Hangi_Tus"]));
            }
            set {
                this["D_Hangi_Tus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public string D_MS {
            get {
                return ((string)(this["D_MS"]));
            }
            set {
                this["D_MS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F3")]
        public global::System.Windows.Forms.Keys D_Baslatma {
            get {
                return ((global::System.Windows.Forms.Keys)(this["D_Baslatma"]));
            }
            set {
                this["D_Baslatma"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F4")]
        public global::System.Windows.Forms.Keys D_Kapatma {
            get {
                return ((global::System.Windows.Forms.Keys)(this["D_Kapatma"]));
            }
            set {
                this["D_Kapatma"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("End")]
        public global::System.Windows.Forms.Keys D_Etkin_Devre {
            get {
                return ((global::System.Windows.Forms.Keys)(this["D_Etkin_Devre"]));
            }
            set {
                this["D_Etkin_Devre"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool D_Arka_Plan {
            get {
                return ((bool)(this["D_Arka_Plan"]));
            }
            set {
                this["D_Arka_Plan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Copyright_Mizer_2020")]
        public string Copyright_Mizer_2020 {
            get {
                return ((string)(this["Copyright_Mizer_2020"]));
            }
            set {
                this["Copyright_Mizer_2020"] = value;
            }
        }
    }
}
